name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Wxo
          template: classic
          # Configura otras opciones si es necesario

      # Paso para mover el archivo SVG generado a una carpeta específica del repositorio
      - name: Move SVG to repository folder
        run: |
          mkdir -p .github/metrics
          mv ./path/to/generated/metrics.svg .github/metrics/metrics.svg

      # Confirmar y subir el archivo SVG a GitHub
      - name: Commit and push SVG
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Add updated GitHub metrics SVG"
          add: ".github/metrics/metrics.svg"
